version: '3.6'

services:
  db:
    command: --log-bin=master --binlog-format=row
    container_name: mariadb
    image: mariadb:10.4.4-bionic
    restart: always
    ports:
      - "33104:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - maria:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d/

  nats:
    image: 'bitnami/nats:latest'
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

#  maxwell:
#    container_name: maxwell
#    image: zendesk/maxwell
#    restart: always
#    depends_on:
#      - db
#      - nats
#    command: ./bin/maxwell --user=root --password=toor --host=db --producer=nats  --nats_url="ml-platform_nats_1:4222"

volumes:
  maria: